plugins {
    id 'java'
}

group = 'com.gearbound.discordlink'
version = '1.1.0'

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

repositories {
    mavenCentral()
    maven { url "https://repo.erdbeerbaerlp.de/repository/maven-public/" }
    maven {url "https://jitpack.io/"}
}
dependencies {
    compileOnly 'de.erdbeerbaerlp:dcintegration.common:3.0.7'

    compileOnly 'org.apache.logging.log4j:log4j-api:2.17.1'

    compileOnly 'de.erdbeerbaerlp:toml4j:2073e86'
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
        )
    }

    archiveBaseName.set('LinkAddon')
    archiveVersion.set(version)
    destinationDirectory.set(file("$buildDir/libs"))
}
